name: ci-tests

on:
  push:
  pull_request:

jobs:
  csharp-and-python:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['8.0.x']

    steps:
      # 1. Checkout source
      - uses: actions/checkout@v4

      # 2. Set up the required .NET SDK
      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      # 3. Restore all dependencies (solution-wide)
      - name: Restore dependencies
        run: dotnet restore

      # 4. Build everything once (Release config)
      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      # 5. Run **all** tests in Server.Tests (StoreTests + ControllerTests)
      #    Remove --filter if you ever add more test projects and want to run them too.
      - name: Run C# test suite
        run: dotnet test Server.Tests/Server.Tests.csproj --configuration Release --no-build --verbosity minimal