name: ci-tests

on:
  push:
  pull_request:

jobs:
  csharp-and-python:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['8.0.x']

    steps:
    # ------------------------------------------------------------------
    # 1.  Checkout repository
    # ------------------------------------------------------------------
    - name: Checkout source
      uses: actions/checkout@v4

    # ------------------------------------------------------------------
    # 2.  .NET build-and-test pipeline
    # ------------------------------------------------------------------
    - name: Set up .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Restore .NET dependencies
      run: dotnet restore

    - name: Build solution (Release)
      run: dotnet build --configuration Release --no-restore

    - name: Run all C# tests
      run: |
        dotnet test Server.Tests/Server.Tests.csproj \
                   --configuration Release \
                   --no-build \
                   --verbosity minimal

    # ------------------------------------------------------------------
    # 3.  Python client test pipeline
    # ------------------------------------------------------------------
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install client dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Client/requirements.txt

    - name: Run Python tests
      run: pytest -q Client
