name: ci-tests

on:
  push:
  pull_request:

jobs:
  store-tests-only:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['8.0.x']

    steps:
      - uses: actions/checkout@v4

      # ---------- .NET ----------
      - name: Install .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Run StoreTests only
        run: |
          dotnet test Server.Tests \
              --configuration Release \
              --no-build \
              --verbosity minimal \
              --filter "FullyQualifiedName~StoreTests"
